title: Master Jet Pressure Washing Ltd.
keywords: >-
  Pressure washing, power washing, Commercial building washes, 
  pavement cleaning, concrete cleaning, gum spot removal, dumpster cleaning, 
  compactor cleaning, building exterior cleaning, warehouse cleaning,
  residential building cleaning
url: "https://masterjet.ca"
phone: 780-239-9979
email: amawer@shaw.ca

exclude: 
  -
    _site-text
  -
    _designs
    
defaults:
  - # All Pages have layout: default
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap