title: Master Jet Pressure Washing Ltd.
keywords: >-
  Pressure washing, building washing, power washing,
  Edmonton pressure washing, Edmonton power washing, building pressure washing Edmonton,
  warehouse pressure washing Edmonton, commercial building washing, 
  Edmonton industrial pressure washing, Edmonton commercial pressure washing, 
  pavement cleaning, concrete cleaning, gum spot removal, dumpster cleaning, 
  compactor cleaning, building exterior cleaning, warehouse pressure washing,
  residential building cleaning, hot pressure washing
url: "https://masterjet.ca"
phone: 780-239-9979
email: amawer@shaw.ca
facebook: https://www.facebook.com/Master-Jet-Pressure-Washing-Ltd-559257914493592/

exclude: 
  -
    _site-text
  -
    _designs
    
defaults:
  - # All Pages have layout: default
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap